TieBreaker AI: tiebreaker_cli Namespace Reference
tiebreaker_cli Namespace Reference
Classes
class DataHub
Functions
str norm (str s)
str|None best_name_match (str query, list[str] candidates)
date_parse_or_none (str|None s)
pd.Series parse_rank_date_col (pd.Series series)
resolve_player_id (DataHub hub, str name_query)
cmd_rank (args, DataHub hub)
cmd_match (args, DataHub hub)
build_parser ()
main (argv=None)
Function Documentation
best_name_match()
str | None tiebreaker_cli.best_name_match (str query, list[str] candidates)
Definition at line 21 of file tiebreaker_cli.py.
References norm().
Referenced by resolve_player_id().
build_parser()
tiebreaker_cli.build_parser ()
Definition at line 291 of file tiebreaker_cli.py.
Referenced by main().
cmd_match()
tiebreaker_cli.cmd_match (args, DataHub hub)
Definition at line 209 of file tiebreaker_cli.py.
References date_parse_or_none(), and resolve_player_id().
cmd_rank()
tiebreaker_cli.cmd_rank (args, DataHub hub)
Definition at line 162 of file tiebreaker_cli.py.
References date_parse_or_none(), and resolve_player_id().
date_parse_or_none()
tiebreaker_cli.date_parse_or_none (str | None s)
Definition at line 29 of file tiebreaker_cli.py.
Referenced by cmd_match(), and cmd_rank().
main()
tiebreaker_cli.main (argv = None)
Definition at line 313 of file tiebreaker_cli.py.
References build_parser().
norm()
str tiebreaker_cli.norm (str s)
Definition at line 18 of file tiebreaker_cli.py.
Referenced by best_name_match().
parse_rank_date_col()
pd.Series tiebreaker_cli.parse_rank_date_col (pd.Series series)
Definition at line 37 of file tiebreaker_cli.py.
Referenced by tiebreaker_cli.DataHub.load_rankings().
resolve_player_id()
tiebreaker_cli.resolve_player_id (DataHub hub, str name_query)
Definition at line 153 of file tiebreaker_cli.py.
References best_name_match().
Referenced by cmd_match(), and cmd_rank().